name: Deployment backend to production
on:
    push:
        branches: [ prod ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          -
            name: checkout code
            uses: actions/checkout@v2
          -
            name: Docker login
            uses: docker/login-action@v2
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
          -
            name: Build and push
            uses: docker/build-push-action@v4
            with:
              context: ./backend
              file: ./backend/Dockerfile
              push: true
              tags: techindustry/attendex:${{ github.sha }}
              build-args: |
                MONGO_URL=${{ secrets.MONGO_URL }}
                JWT_SECRET=${{ secrets.JWT_SECRET }}
          -
            name: Deploy to the vps
            uses: appleboy/ssh-action@v1.2.1
            with:
              host: ${{ secrets.HOST }}
              username: root
              key: ${{ secrets.SSH_PRIVATE_KEY }}
              script: |
                docker pull techindustry/attendex:${{ github.sha }}
                docker stop attendex
                docker rm attendex
                docker run --name attendex -d -p 8000:8000 techindustry/attendex:${{ github.sha }}